name: flut1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  url_launcher: ^6.0.20
  qr_flutter: ^4.0.0
  font_awesome_flutter: ^10.4.0
  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.0
  provider: ^6.0.3
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.2
  flutter_typeahead: ^5.2.0
  modal_bottom_sheet: ^3.0.0
  responsive_framework: ^1.5.1
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/pictures/

  - assets/background/
